name: Seetale
favicon: null
layout_spectrum: 0.9204032309353352
typography_spectrum: 0.4700756643433124
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7042295548599213
  lightness: 0.40950675145722926
  saturation: 0.992094422923401
  rhythmicContrast: 0.40458783181384206
purpose: []
